cache visibility check results for reuse within a single operation
theKashey/focus-lock pull request #24
Opened 2021-05-08 21:11 UTC by just-boris

My naive attempt to fix: theKashey/react-focus-lock#151

I confirmed this in my real application case, it prevents Jest test from getting timed out.

2021-05-09 01:09 UTC, theKashey commented
> size-limit is failing the build. Is configured a bit tight.

Thank you for making this change and proving that it is a fix. However, before we proceed  I need to do one more little thing - I want to track the existing "complexity" to understand the difference.

> PS: technically speaking there is a slightly better way to manage this use case - wrap the single memoization target - `isVisible` with [kashe](https://github.com/theKashey/kashe), and _switch universes_ at the top (`visibilityCache`) to throw-away ones using `inboxed` helper.
Unfortunately, that is +1kb of the code, which is +30% to the total size of this library.

2021-05-09 01:52 UTC, theKashey commented
Complexity check has been merged - https://github.com/theKashey/focus-lock/pull/25 - and everything is VERY BAD

Please merge with a master and lets see much much crap will be gone.

2021-05-09 01:54 UTC, theKashey commented on src/utils/is.ts
> +    if(cached) {
that is working only for "true" cases, while false is legit as well
```suggestion
    if (cached!==undefined) {
```

2021-05-09 01:56 UTC, theKashey commented on src/utils/is.ts
> +    const result = node === document ||
can we extract the actual check to the separate function?
Technically you can just rename "the old one" and then build a cached version next to it.

2021-05-09 01:56 UTC, theKashey requested changes
- one suggestion
- and one new test to pass

2021-05-10 09:36 UTC, theKashey approved these changes

2021-05-10 23:13 UTC, merged

2021-05-12 20:00 UTC, just-boris commented
ok, so the fix got merged, but to benefit from it we need to have a release

Is there anything blocking this?

2021-05-13 05:52 UTC, theKashey commented
I was just not satisfied with the result numbers and added a few more tests.
As a result I've found that with the very last commit you broke nested memoization - it was caching result only for the very first noded. Not everything.

The result numbers are WAY better, and (again) that's all thanks to you 🎉

2021-05-13 05:53 UTC, theKashey commented on src/utils/is.ts
>    node === document ||
oh no. Nested call is to the same "uncached" isVisible

2021-05-13 05:58 UTC, theKashey commented
Published as focus-lock@0.9.1

2021-05-13 07:46 UTC, just-boris commented
Very nice! Thanks for doing proper quality assurance of my code :)